apiVersion: v1
kind: ConfigMap
metadata:
  name: argo-workflow-controller-configmap
  namespace: argo
data:
  config: |
    artifactRepository:
    metricsConfig:
      enabled: true
      path: /metrics
      port: 8080
