apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-workflow-controller
  namespace: argo
  labels:
    app: argo-workflow-controller
spec:
  selector:
    matchLabels:
      app: argo-workflow-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: argo-workflow-controller
    spec:
      serviceAccountName: "argo"
      containers:
        - name: controller
          image: "argoproj/workflow-controller:v2.3.0"
          imagePullPolicy: Always
          command: [ "workflow-controller" ]
          args:
          - "--configmap"
          - "argo-workflow-controller-configmap"
          - "--executor-image"
          - "argoproj/argoexec:v2.3.0"
          - "--loglevel"
          - "info"
          - "--gloglevel"
          - "0"
          env:
          - name: ARGO_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
