apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-ui
  namespace: argo
  labels:
    app: argo-ui
spec:
  selector:
    matchLabels:
      app: argo-ui
  replicas: 1
  template:
    metadata:
      labels:
        app: argo-ui
    spec:
      serviceAccountName: "argo-ui"
      containers:
        - name: ui
          image: "argoproj/argoui:v2.3.0"
          imagePullPolicy: Always
          env:
          - name: FORCE_NAMESPACE_ISOLATION
            value: "true"
          - name: IN_CLUSTER
            value: "true"
          - name: ARGO_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: BASE_HREF
            value: /
