apiVersion: v1
kind: Service
metadata:
  name: argo-ui
  namespace: argo
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8001
  selector:
    app: argo-ui
  sessionAffinity: None
  type: ClusterIP
