apiVersion: v1
kind: Secret
metadata:
  name: ssh-files
  namespace: argo
data:
  id_rsa: {{ .Values.global.id_rsa | b64enc }}
  id_rsa.pub: {{ .Values.global.id_rsa_pub | b64enc }}
  known_hosts: {{ .Values.global.known_hosts | b64enc }}
type: Opaque