apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hasura
    hasuraService: custom
  name: hasura
  namespace: hasura
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hasura
  template:
    metadata:
      labels:
        app: hasura
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node_pool
                    operator: NotIn
                    values:
                      - load-tests-workers-slaves
                  - key: node_pool
                    operator: NotIn
                    values:
                      - load-tests-workers-masters
      containers:
      - image: hasura/graphql-engine:v2.4.0
        imagePullPolicy: IfNotPresent
        name: hasura
        env:
        - name: HASURA_GRAPHQL_DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: hasura-secrets
              key: HASURA_GRAPHQL_DATABASE_URL
        - name: HASURA_GRAPHQL_ADMIN_SECRET
          valueFrom:
            secretKeyRef:
              name: hasura-secrets
              key: HASURA_GRAPHQL_ACCESS_KEY
        - name: HASURA_GRAPHQL_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: hasura-secrets
              key: HASURA_GRAPHQL_JWT_SECRET
        ## enable the console served by server
        - name: HASURA_GRAPHQL_ENABLE_CONSOLE
          value: "true"
        ## enable debugging mode. It is recommended to disable this in production
        - name: HASURA_GRAPHQL_DEV_MODE
          value: {{ .Values.hasura.environment.HASURA_GRAPHQL_DEV_MODE }}
        - name: HASURA_GRAPHQL_ENABLE_REMOTE_SCHEMA_PERMISSIONS
          value: "false"
        - name: BOLT_API_GRAPHQL
          value: http://bolt-api.bolt-api.svc.cluster.local/graphql
        - name: BOLT_API_EXECUTION_STATE_CHANGE
          value: http://bolt-api.bolt-api.svc.cluster.local/webhooks/execution/update
        - name: BOLT_API_CONFIGURATION_PARAM_CHANGE
          value: http://bolt-api.bolt-api.svc.cluster.local/webhooks/configuration_param/update
        - name: BOLT_API_EXECUTION_REQUESTS_INSERT
          value: http://bolt-api.bolt-api.svc.cluster.local/webhooks/execution_requests/insert
        - name: BOLT_API_EXECUTION_STAGE_LOG_INSERT
          value: http://bolt-api.bolt-api.svc.cluster.local/webhooks/execution_stage_log/insert
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
